### ISSUE TITLE
OMPL::OMPLInterfacePlanner PRM version does not terminate when solution is found

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [KavrakiLab/robowflex#20]
I don't know the exact reason but it sees that it defaults to the PRMstar version

**Comment by BryceStevenWilley** [comment]
Quick guess is that planner config name is `PRMstar`, which is shorter than `PRMkConfig`, which is probably the default. Setting the planner to a name like `PRM` matches the shortest planner config name.  IMO, the best solution is to consistently have `kConfig` or not in all of the planner config names.

**Comment by ChamzasKonstantinos** [comment]
This might be a Moveit issue, I just checked with the default moveit configs for both fetch and ur5 andthe PRM  used all the time even for the simplest problems. Maybe my Moveit installation is messed up. Can someone reproduce? Also where are these config files? `PRMkConfigDefault` for example?

**Comment by BryceStevenWilley** [comment]
After looking into it for a bit, I believe that PRM's default behavior is to use all of the time given to it to plan.  There's not a fix in default MoveIt right now (it's a small enough change that I might add it later), but you can change the code in 2 places to fix:
* Add a new [OptimizationObjective](https://github.com/KavrakiLab/moveit/blob/no-interpolate/moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp#L405) that returns the first found path.
* Make a new [planner config](https://github.com/KavrakiLab/barrett_moveit/blob/master/barrett_wam_moveit_config/config/ompl_planning.yaml#L27), usually found in `<robot>_moveit_config/config/ompl_planning.yaml` that uses this OptimizationObjective.

Then just use this new planner config instead of `PRMkConfigDefault`.

**Comment by zkingston** [comment]
Yeah, we were looking into this a bit yesterday and think that the default optimization objective that PRM uses (`PathLengthOptimizationObjective`) has its default threshold set to `0.0` (see the base constructor for `OptimizationObjective`. In `PRM::maybeConstructSolution`, the optimization objective is checked for satisfaction (`isSatisifed`), which should always return false unless the threshold is modified.

**Comment by ChamzasKonstantinos** [comment]
Yeah I fixed by setting directly the cost to infinity. Thank you both !
